Repository eslint/eslint-release, pull requests merged in 2021-04, with the labels that each got.

#52 Build: Update CI to point to main branch
  .github/workflows/ci.yml
Labels: triage

#54 Chore: upgrade eslint-config-eslint@7.0.0
  .eslintrc.yml
  .github/workflows/ci.yml
  package.json
Labels: chore

#53 Fix: Omit sponsors sync from changelog
  .eslintrc.yml
  lib/release-ops.js
  tests/lib/release-ops.js
Labels: accepted, bug
